### ISSUE TITLE
Improve scroll box and make example demonstrating how it works

### ISSUE THREAD

**Issue by PsichiX** [PsichiX/raui#18]
Altho we have scroll box solution, it works only in tests, when put in real life application interactions aren't possible - debug and fix it, also provide an example of how to use it (preferably in TODO app demo)

**Comment by PsichiX** [comment]
during extensive layout debugging i've found that the main reason is that FlexBox (and GridBox too) is minimum-size focused in default layout engine. This isn't bad on itself, but makes harder to make list-like layouts that fill all available space. i will add a flag into FlexBox and GridBox that tells if we want to fill the entire space or get the minimal required space that their children occupy. Adding handlers of these layout variants shouldn't take longer than few hours with tests included. Will present results as fast as i get them.

**Comment by PsichiX** [comment]
no, i was wrong - FlexBox and GridBox are filling the space too - this is some problem with Material components that somehow forces use of minimum-size approach, when i replace Material components with core components everything works fine (and that's why i've got it working in tests but not in the TODO app) - gonna investigate what is wrong on the Material components side.

**Comment by PsichiX** [comment]
actually i'm so much dumb..
```rust
let bar_props = FlexBoxItemLayout {
    grow: 0.0,
    shrink: 0.0,
    ..Default::default()
};

let tasks_props = Props::new(FlexBoxItemLayout {
    grow: 0.0,
    shrink: 0.0,
    ..Default::default()
})
.with(TasksProps { tasks });
```
i totally ignored the part of code where i put task list into non-growable flexbox layout 🤦 

ok, there is no problem to fix, except my brain :D

**Comment by PsichiX** [comment]
almost there - right now i'm adding navigable scroll paper to Material library, and then i have to quick-fix amount of relative scrolling with pointer wheel events

**Comment by zicklag** [comment]
Awesome! I'm probably going to need this soon-ish, so perfect timing. :smile:

**Comment by PsichiX** [comment]
![raui-scroll-box](https://user-images.githubusercontent.com/2111867/116824332-deb1de00-ab89-11eb-870c-8a3501954c7b.gif)

Themed ScrollBox is working now :D gonna take a break and publish new version later at night 🎉

**Comment by PsichiX** [comment]
fixed relative units-based scroll problem (amount of relative scroll was dependent on the difference in sizes between scroll box and its content) and added locking widget selection (that one is useful for dragging stuff so for example on scrollbar button press you lock selection and you can drag outside the scroll bar and it still gets pointer move signal without selecting other widgets on pointer hover).

**Comment by PsichiX** [comment]
new version published, closing the issue :D
