### ISSUE TITLE
Questions About The New ClipPush and ClipPop

### ISSUE THREAD

**Issue by zicklag** [PsichiX/raui#23]
I'm a little confused about the `matrix` field of [`BatchClipRect`](https://docs.rs/raui-tesselate-renderer/0.34.0/raui_tesselate_renderer/tesselation/struct.BatchClipRect.html). My first thought was that I would just take the 3rd and 7th fields of the matrix as the `x` and `y` as if it were a transform matrix, but I can see that for the tetra renderer you do a block of math to calculate the screen clipping rectangle from the `matrix`.

I might just be ignorant but would it make sense for the tesselator renderer to do that math for you and then just return the clipping rectangle as an `x`, `y`, `width`, and `height`?

**Comment by zicklag** [comment]
Oh, I get the math now, you are transforming the rect including position and scale. When I figured out `br` meant bottom right, etc. it started to make sense.

**Comment by PsichiX** [comment]
there is this thing about clip rect that it doesn't has to have right angles - for example if there is some transform in the chain of widgets that for example rotates or do other crazy things, these 4 vectors are telling where in screen space each of the clip rect vertices is rotated. usually it is to allow renderers to make a mask using stencil buffer that will clip space to the exact area given widget covers after all these transforms are applied.

**Comment by zicklag** [comment]
Ah, I didn't think of that. Sounds reasonable, then. :+1:
