### ISSUE TITLE
Fix readme to reflect new hooks macros usage

### ISSUE THREAD

**Issue by PsichiX** [PsichiX/raui#6]
Readme is still showing old macros used in examples

**Comment by PsichiX** [comment]
@zicklag i was playing with the idea that we could actually generate readme file from some template, that will inject rust code from rust code files that we can format and test.
i was trying to put readme content in crate level docs inside `/*! */` but that isn't supported by nightly fmt tool, it works only with `//!` and putting it on every line actually makes the whole work on readme counter productive imo. do you have an idea of tools that are able to produce readme file with code injected from other files or rather we might want to make a simple CLI tool that just reads template and injects rust code files from some `examples` folder by their path?

**Comment by zicklag** [comment]
Yeah, I've run into this problem before. So far I've been putting the whole README in the `lib.rs` doc comment and using [`cargo readme`](https://github.com/livioribeiro/cargo-readme) to move it into the README using a template.

As you say it is frustrating to copy the example code into the doc comment, though. In the projects I've had so far I would usually copy and paste from my example code into the doc comment and then use the `alt-click` in VSCode to multi-edit the character column before the example and add the `//!`.

With that strategy you ensure the README examples are tested, but it's not the nicest experience to update the README code.

---

One thing that comes to mind would be if we could make a macro that we put in the `lib.rs` file that would generate the doc comment from a markdown file template that includes examples using file paths like you mentioned. Then I guess we would need a corresponding CLI that uses the same substitution logic to generate the README. This is such a common problem it seems worth trying to solve.

**Comment by PsichiX** [comment]
hmm how about: generating readme using mdbook? 🤔

**Comment by zicklag** [comment]
That's an interesting idea. :thinking:

Because MDBook has a JSON backend ( if I remember correctly ), and because it has the ability to grab Rust files from external files, then that would cover everything except the `lib.rs` doc comment, but we could easily add that to the same automation that generates the README. That might be a good idea. We'd probably still need a CLI to actually do it.

**Comment by PsichiX** [comment]
i'm already making the CLI tool, that's gonna be super easy :D
my current idea is that tool gets input MD file, uses regex to search for:

    ```rust: source
    ./examples/snippets/foo.rs
    ```

and replaces it with:

    ```rust
    <file content>
    ```

do we need something else?

**Comment by zicklag** [comment]
The other thing that would be nice would be to replace all of the first lines in the `lib.rs` that start with `//!` with the contents of the markdown file so that it matches the README.

**Comment by PsichiX** [comment]
so essentially we are aiming for:
- make a readme.md template with code blocks that points to snippets from files
- CLI tool bakes template into readme.md
- inject rendered readme.md into lib.rs by replacing all `//!` lines with the readme content as docs comments.
right?

**Comment by zicklag** [comment]
Yep! I think so. :)

**Comment by PsichiX** [comment]
ok, gonna make it and we will test how it plays with the CI

**Comment by zicklag** [comment]
Something that I like to use for my repos now is a [`justfile`](https://github.com/casey/just) which is kind of like a sensible makefile that is actually just a task-runner. Then I just add tasks such as updating the README to the `justfile` so that there's a central list of these kinds of tasks and so that it's super easy to run whenever I need to for dev, etc.

It's not crucial or anything, but you might find it useful.

**Comment by PsichiX** [comment]
for makefile-like tasks i've been using `cargo make` for past few years, i wonder how it is different with `justfile` 🤔

**Comment by zicklag** [comment]
Ah, I used cargo make for a bit too, but I found the TOML format to be rather annoying and confusing. The `justfile`s I've been using are very simple. I just like the asthetic:

```makefile
dev_features:='--features bevy/dynamic'

build:
    cargo build {{dev_features}}

build-release:
    cargo build --release
    strip target/release/skipngo

build-cross-windows:
    cargo build --target x86_64-pc-windows-gnu

build-release-cross-windows:
    cargo build --release --target x86_64-pc-windows-gnu
    strip target/x86_64-pc-windows-gnu/release/skipngo.exe

build-web:
    cargo build --target wasm32-unknown-unknown
    wasm-bindgen --out-dir target/wasm --target web target/wasm32-unknown-unknown/debug/skipngo.wasm
    cp wasm_resources/index.html target/wasm/index.html
    mkdir -p target/wasm

build-release-web:
    cargo build --target wasm32-unknown-unknown --release
    wasm-bindgen --out-dir target/wasm-dist --no-typescript --target web target/wasm32-unknown-unknown/release/skipngo.wasm
    cp wasm_resources/index.html target/wasm-dist/index.html

run *args:
    cargo run {{dev_features}} -- {{args}}

run-web: build-web
    @echo "Debug link: http://localhost:4000?RUST_LOG=debug"
    basic-http-server -x target/wasm
```

**Comment by PsichiX** [comment]
hmm, gonna think about it, since right now i'm using .sh files to actually do these tasks, this thing might be helpful 🤔

**Comment by PsichiX** [comment]
markdown baking was published to separate crate: https://github.com/PsichiX/md-bakery
and use of it is added in new version, injecting baked readme into crate-level docs comments using proc macros is gonna be prototyped and implemented in new dedicated PR.
