### ISSUE TITLE
Do We Want to Use Glob Patterns for Workspace Members?

### ISSUE THREAD

**Issue by zicklag** [PsichiX/raui#8]
https://github.com/PsichiX/raui/blob/bdabe92953c80ea52e67ffd9f8006807d79eb292/Cargo.toml#L90-L106

Just a thought, do we want to replace the above code with:

```toml
members = [
    "raui-*",
    "demos/*"
]
```

**Comment by PsichiX** [comment]
i would like to explicitly declare what projects are members of the workspace. does glob patterns gives us some other benefits than less code?

**Comment by zicklag** [comment]
Probably not, it was just a personal preference, but I can totally understand it either way. :+1:
